### ISSUE TITLE
Broken Vimeo support

### ISSUE THREAD

**Issue by keskad** [JakeWharton/py-videodownloader#18]
Hello, i cant download any video using your library/application.

``` bash
webnull@tealc ~ $ videodownloader http://vimeo.com/30096787 -h
videodownloader-2.0.0 - by Jake Wharton <jakewharton@gmail.com>

Usage: videodownloader -p PROVIDER [-f FMT] [-d DIR] videoID [... videoID]

Options:
  -h, --help            show this help message and exit
  -e EXT, --ext=EXT     Manually override video extension.
  -f FORMAT, --format=FORMAT
                        Format of video to download. Run with no video IDs for
                        a provider specific list.
  -t TITLE, --title=TITLE
                        Manually override video title.
  -p PROVIDER, --provider=PROVIDER
                        Online provider from where to download the video.
                        (Available: 'Vimeo', 'YouTube')
  --debug               Enable debugging output.
webnull@tealc ~ $ videodownloader http://vimeo.com/30096787 -p vimeo
videodownloader-2.0.0 - by Jake Wharton <jakewharton@gmail.com>

Traceback (most recent call last):
  File "/usr/bin/videodownloader", line 9, in <module>
    load_entry_point('videodownloader==2.0.0', 'console_scripts', 'videodownloader')()
  File "/usr/lib/python2.7/site-packages/videodownloader/main.py", line 58, in main
    v = provider(video, title=options.title, format=options.format, ext=options.ext, debug=options.is_debug)
TypeError: 'module' object is not callable
webnull@tealc ~ $ videodownloader http://vimeo.com/30096787 -p Vimeo
videodownloader-2.0.0 - by Jake Wharton <jakewharton@gmail.com>

Traceback (most recent call last):
  File "/usr/bin/videodownloader", line 9, in <module>
    load_entry_point('videodownloader==2.0.0', 'console_scripts', 'videodownloader')()
  File "/usr/lib/python2.7/site-packages/videodownloader/main.py", line 58, in main
    v = provider(video, title=options.title, format=options.format, ext=options.ext, debug=options.is_debug)
  File "/usr/lib/python2.7/site-packages/videodownloader/providers/vimeo.py", line 36, in __init__
    self._xml = ElementTree.fromstring(super(Vimeo, Vimeo)._download(url).read())
  File "/usr/lib/python2.7/site-packages/videodownloader/providers/__init__.py", line 139, in _download
    return urllib2.urlopen(urllib2.Request(url, headers=Provider.HEADERS))
  File "/usr/lib/python2.7/urllib2.py", line 126, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 406, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 519, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 444, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 378, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 527, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 404: Not Found
```

**Comment by peterswanson** [comment]
I have the same issue ...
